/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            "colors": {
                "inverse-surface": "#ede0e0",
                "secondary-fixed": "#ffdad6",
                "on-tertiary-fixed": "#241a00",
                "on-tertiary-fixed-variant": "#594400",
                "surface-container-highest": "#3a2f2f",
                "on-primary-fixed-variant": "#b71c1c",
                "surface-container-high": "#2b2020",
                "on-tertiary": "#3e2e00",
                "on-secondary-fixed": "#2d0a0a",
                "on-secondary-container": "#ffcdd2",
                "tertiary": "#f5c518",
                "surface-dim": "#120e0e",
                "tertiary-fixed-dim": "#f5c518",
                "primary-fixed": "#ffdad6",
                "on-tertiary-container": "#7f4f00",
                "surface-tint": "#ff5252",
                "on-primary-fixed": "#4a0000",
                "inverse-on-surface": "#2d1f1f",
                "on-primary": "#ffffff",
                "inverse-primary": "#c62828",
                "primary": "#ff5252",
                "secondary": "#ffab91",
                "surface": "#120e0e",
                "surface-bright": "#3a2f2f",
                "surface-variant": "#302424",
                "on-error": "#ffffff",
                "secondary-container": "#5c1a1a",
                "surface-container-low": "#1c1515",
                "on-primary-container": "#ffcdd2",
                "surface-container-lowest": "#0d0808",
                "error": "#ffb4ab",
                "on-error-container": "#ffdad6",
                "background": "#120e0e",
                "outline-variant": "#4d3535",
                "primary-fixed-dim": "#ff5252",
                "tertiary-fixed": "#ffd966",
                "on-surface-variant": "#c9b8b8",
                "on-secondary-fixed-variant": "#6b3333",
                "outline": "#8c7070",
                "secondary-fixed-dim": "#ffab91",
                "tertiary-container": "#c9a000",
                "primary-container": "#c62828",
                "error-container": "#93000a",
                "surface-container": "#201818",
                "on-secondary": "#4a0000",
                "on-surface": "#ede0e0",
                "on-background": "#ede0e0"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "md": "16px",
                "xl": "48px",
                "xs": "4px",
                "base": "4px",
                "lg": "24px",
                "container-margin": "32px",
                "sm": "8px",
                "gutter": "16px"
            },
            "fontFamily": {
                "headline-lg": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "label-bold": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "display": ["Inter", "sans-serif"],
                "label-muted": ["Inter", "sans-serif"],
                "body-sm": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "headline-sm": ["Inter", "sans-serif"]
            },
            "fontSize": {
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-muted": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}